# Run task on Github
# @name runScanGithub

@apiKey = {{$dotenv API_KEY}}
@githubToken = {{$dotenv GITHUB_TOKEN}}
@githubRepoName = {{$dotenv GITHUB_REPO_NAME}}
@githubCommitSha = {{$dotenv GITHUB_COMMIT_SHA}}
@githubAssignee = {{$dotenv GITHUB_ASSIGNEE}}

POST {{apiUrl}}/run-scan
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "source": "github",
  "args": {
    "github_token": "{{githubToken}}",
    "github_repo_name": "{{githubRepoName}}",
    "github_commit_sha": "{{githubCommitSha}}",
    "github_assignee": "{{githubAssignee}}"
  }
}

###

# Get Status
# @name getStatusGithub

@githubScanId = {{runScanGithub.response.body.scan_id}}

POST {{apiUrl}}/scan-status
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "scan_id": "{{githubScanId}}"
}

###

@bitbucketRepoSlug = {{$dotenv BITBUCKET_REPO_SLUG}}
@bitbucketWorkspace = {{$dotenv BITBUCKET_WORKSPACE}}
@bitbucketProjectKey = {{$dotenv BITBUCKET_PROJECT_KEY}}
@bitbucketCommit = {{$dotenv BITBUCKET_COMMIT}}

# Run task on Bitbucket
# @name runScanBitbucket

POST {{apiUrl}}/run-scan
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "source": "bitbucket",
  "args": {
    "bitbucket_repo_slug": "{{bitbucketRepoSlug}}",
    "bitbucket_workspace": "{{bitbucketWorkspace}}",
    "bitbucket_project_key": "{{bitbucketProjectKey}}",
    "bitbucket_commit": "{{bitbucketCommit}}"
  }
}

###

# Get Status
# @name getStatusBitbucket

@bitbucketScanId = {{runScanBitbucket.response.body.scan_id}}

POST {{apiUrl}}/scan-status
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "scan_id": "{{bitbucketScanId}}"
}

###

# Run task on CLI
# @name runScanCLI

@apiKey = {{$dotenv API_KEY}}
@batchId = {{$dotenv BATCH_ID}}

POST {{apiUrl}}/run-scan
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "source": "cli",
  "args": {
    "batch_id": "{{batchId}}"
  }
}

###

# Get Status
# @name getStatusCLI

@apiKey = {{$dotenv API_KEY}}
@cliScanId = {{runScanCLI.response.body.scan_id}}

POST {{apiUrl}}/scan-status
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "scan_id": "{{cliScanId}}"
}