# Run task
# @name runScan

@apiKey = {{$dotenv API_KEY}}
@githubToken = {{$dotenv GITHUB_TOKEN}}
@githubRepoName = {{$dotenv GITHUB_REPO_NAME}}
@githubCommitSha = {{$dotenv GITHUB_COMMIT_SHA}}
@githubAssignee = {{$dotenv GITHUB_ASSIGNEE}}

POST {{apiUrl}}/run-scan
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "source": "github",
  "args": {
    "github_token": "{{githubToken}}",
    "github_repo_name": "{{githubRepoName}}",
    "github_commit_sha": "{{githubCommitSha}}",
    "github_assignee": "{{githubAssignee}}"
  }
}

###

# Get Status
# @name getStatus

@scanId = {{runScan.response.body.scan_id}}

POST {{apiUrl}}/scan-status
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "scan_id": "{{scanId}}"
}
